# Generated by Django 3.0.8 on 2020-08-01 08:37

from django.db import migrations, models

def create_test_cars(apps, schema_editor):
    Car = apps.get_model("fleet", "Car")
    Car.objects.bulk_create([
        Car(brand = "Volvo", year = "2010", petrol = 1, model="XC60"),
        Car(brand="Mistrzubiszi", year="2012", petrol=2, model="Lancer"),
    ])



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('petrol', models.IntegerField(choices=[(0, 'LPG'), (1, 'DIESEL'), (2, 'BENZINE'), (3, 'ELECTRIC')])),
            ],
        ),
        migrations.RunPython(create_test_cars)
    ]
