# Generated by Django 3.0.8 on 2020-08-01 11:34

from django.db import migrations, models
import django.db.models.deletion



def create_test_company(apps, schema_editor):
    Company = apps.get_model("fleet", "Company")
    Company.objects.bulk_create([
        Company(name = "Firma_1", tax_number="1234567890"),
        Company(name = "Firma_2", tax_number="2345678901"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tax_number', models.IntegerField()),
            ],
        ),

        migrations.RunPython(create_test_company),

        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet.Company'),
        ),
    ]
