# Generated by Django 3.0.8 on 2020-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20200801_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default='FIRMA XXX', on_delete=django.db.models.deletion.CASCADE, to='fleet.Company'),
        ),
    ]
